language: go

sudo: false

go: 
- 1.11

install:
- make deps

script:
- make build

before_deploy:
- tar czvf meshbird-$TRAVIS_TAG.darwin-amd64.tar.gz bin/meshbird

deploy:
- provider: releases
  file: meshbird-$TRAVIS_TAG.darwin-amd64.tar.gz
  api_key: $GITHUB_OAUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true