---
- name: install meshbird
  shell: 'curl http://meshbird.com/install.sh | sh'

- name: install upstart
  template: src=upstart.conf.j2 dest=/etc/init/meshbird.conf owner=root group=root mode=0644

- name: start meshbird
  service: name=meshbird state=restarted

- name: restart mongo
  service: name=mongod state=restarted

- name: get ip
  shell: 'MESHBIRD_KEY=77cdb4790754e187a8e41fdcde0cee8c0a070000ffff0000 meshbird ip >> /etc/motd.tail'
