---
- name: Add mongo key
  apt_key: keyserver="hkp://keyserver.ubuntu.com:80" id="7F0CEB10" state=present
  tags:
    - packages

- name: Add mongodb repository
  apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.0 multiverse" state=present update_cache=true
  tags:
    - packages

- name: Install mongodb
  apt: "name=mongodb-org={{ mongodb_version }} state=present"
  notify:
    - restart mongodb
  tags:
    - packages

- name: Create mongodb data folder
  file: path={{ mongodb_dbPath }} state=directory mode=0755 owner={{ mongodb_user }} group={{ mongodb_group }}
  when: mongodb_dbPath is defined
  tags:
    - configuration

- name: Write mongod.conf
  template: src=mongod.conf.j2 dest=/etc/mongod.conf owner={{ mongodb_user }} group={{ mongodb_group }} mode=0644
  notify:
    - restart mongodb
  tags:
    - configuration

- name: Mongodb service state
  service: name=mongod state=started enabled=yes
  tags:
    - configuration
